# Data Cleaning

In [1]:
import utils
import pandas as pd
import numpy as np

/Users/jenniferle/Downloads/Github/Opinion-Survey-Analysis/utils.py:4: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df_combined = pd.read_csv('Datasets/combined_dataset.csv')

In [21]:
# stop number of columns at the end that don't have the year in the column name
def remove_year_from_column_name(dataset, stop):
    list_columns = list(dataset.columns)

    for i in range(0,len(list_columns)-stop):
        list_columns[i] = list_columns[i][:-5]

    dataset.columns = list_columns
    
def import_and_combine_datatsets():
    # Save each .sav as a data frame
    df_20 = pd.read_spss("Datasets/NPORS-2020/dataset.sav")
    df_21 = pd.read_spss("Datasets/NPORS-2021/dataset.sav")
    df_22 = pd.read_spss("Datasets/NPORS-2022/dataset.sav")
    df_23 = pd.read_spss("Datasets/NPORS-2023/dataset.sav")
    df_24 = pd.read_spss("Datasets/NPORS-2024/dataset.sav")
    df_25 = pd.read_spss("Datasets/NPORS-2025/dataset.sav")

    # convert .sav to .csv
    utils.write_to_file(df_20,"Datasets/NPORS-2020/dataset_20.csv")
    utils.write_to_file(df_21,"Datasets/NPORS-2021/dataset_21.csv")
    utils.write_to_file(df_22,"Datasets/NPORS-2022/dataset_22.csv")
    utils.write_to_file(df_23,"Datasets/NPORS-2023/dataset_23.csv")
    utils.write_to_file(df_24,"Datasets/NPORS-2024/dataset_24.csv")
    utils.write_to_file(df_25,"Datasets/NPORS-2025/dataset_25.csv")

    # Remove the year from column name to keep naming consistant
    remove_year_from_column_name(df_20, 5)
    remove_year_from_column_name(df_21, 2)

    # ensure columns recording the same data have the same name
    # so there aren't duplicate columns when appending datasets
    df_20 = df_20.rename(columns={
        'SEXASK':'GENDER', 
        'EDUC_ACS':'EDUCATION',
        'REGION_NAME':'REGION'
    })
    df_21 = df_21.rename(columns={

    })
    df_22 = df_22.rename(columns={
        'CREGION':'REGION'
    })

    df_23 = df_23.rename(columns={
        'BASEWT':'BASEWEIGHT', 
        'INC_SDT1':'INCOME',
        'CREGION':'REGION'
    })

    df_24 = df_24.rename(columns={
        'BASEWT':'BASEWEIGHT', 
        'INC_SDT1': 'INCOME',
        'SMUSEa' : 'SMUSE_a','SMUSEd' : 'SMUSE_d','SMUSEg' : 'SMUSE_g','SMUSEj' : 'SMUSE_j',
        'SMUSEb' : 'SMUSE_b','SMUSEe' : 'SMUSE_e','SMUSEh' : 'SMUSE_h','SMUSEk' : 'SMUSE_k',
        'SMUSEc' : 'SMUSE_c','SMUSEf' : 'SMUSE_f','SMUSEi' : 'SMUSE_i',
        'CREGION':'REGION'
    })

    df_25 = df_25.rename(columns={
        'BASEWT':'BASEWEIGHT', 
        'INC_SDT1': 'INCOME',
        'CREGION':'REGION'
    })

    # add year columns to all datasets
    df_20['YEAR'] = 2020
    df_21['YEAR'] = 2021
    df_22['YEAR'] = 2022
    df_23['YEAR'] = 2023
    df_24['YEAR'] = 2024
    df_25['YEAR'] = 2025

    social_medias = ['SMUSE_a','SMUSE_b','SMUSE_c','SMUSE_d','SMUSE_e',
          'SMUSE_f','SMUSE_g','SMUSE_h','SMUSE_i','SMUSE_j','SMUSE_k']
    
    dataframes = [df_20,df_21,df_22,df_23,df_24,df_25]

    # for each dataset and for each social media, we want to replace null 
    # values with "Refused" if the social media was asked
    for i in range(len(dataframes)) :
        for social_media in social_medias:
            df = dataframes[i]
            # check if social media column exists
            if social_media in df.columns:
                df[social_media] = df[social_media].astype(str)
                df[social_media] = df[social_media].replace({"nan":"Refused"})

    # Combine (append) all datasets together
    df_combined = pd.concat([df_20, df_21, df_22, df_23, df_24, df_25])

    return df_combined

In [24]:
df_combined = import_and_combine_datatsets()
print(df_combined.shape)
df_combined.head()

(28469, 120)

,RESPID,LANGUAGE,INTERVIEW_START,INTERVIEW_END,ECON1MOD,ECON1BMOD,TYPOLOGYb,COVIDWORK_a,COVIDWORK_b,COMATTACH,...,UNITY,INFRASPEND,GAMBLERESTR,GPT1,DEVICE1A,ATTENDPER,GOVPROTCT,FIN_SIT,AGEGRP,VOTED2024
0,1.0,English,2020-06-03,2020-06-03 10:58:13,Good,About the same,Business corporations make too much profit,"No, has not happened","No, has not happened",Somewhat attached,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,English,2020-06-03,2020-06-03 13:59:15,Only fair,Worse,Business corporations make too much profit,"Yes, has happened","Yes, has happened",Very attached,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,English,2020-06-03,2020-06-03 15:09:45,Poor,Worse,Business corporations make too much profit,"Yes, has happened","Yes, has happened",Not at all attached,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,English,2020-06-03,2020-06-03 15:07:33,Only fair,Worse,Business corporations make too much profit,"No, has not happened","No, has not happened",Not at all attached,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,English,2020-06-03,2020-06-03 15:41:05,Good,Better,Business corporations make too much profit,"Yes, has happened","Yes, has happened",Somewhat attached,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
def remove_and_rename_columns(df_combined):
    # Keep relevent columns only
    df_combined = df_combined[[
        'RESPID','YEAR','AGE','AGEGRP','GENDER','RACECMB', # basic demographics
        'INCOME','EDUCATION', 'REGION','RELIG', 'PARTY', # other useful demographics 
        'RELIMP', 'PRAY', 'MARITAL', # other features
        'SMUSE_a', 'SMUSE_b', 'SMUSE_c', 'SMUSE_d', 'SMUSE_e', 'SMUSE_f', # social media use
        'SMUSE_g','SMUSE_h','SMUSE_i','SMUSE_j','SMUSE_k',
        'ECON1MOD', 'ECON1BMOD', # we want to study how this changes over time
        'BASEWEIGHT', 'WEIGHT' # weights 
    ]]
    # rename columns
    df_combined = df_combined.rename(columns={
        'SMUSE_a':'FACEBOOK',
        'SMUSE_b':'YOUTUBE',
        'SMUSE_c':'TWITTER',
        'SMUSE_d':'INSTAGRAM',
        'SMUSE_e':'SNAPCHAT',
        'SMUSE_f':'WHATSAPP',
        'SMUSE_g':'LINKEDIN',
        'SMUSE_h':'PINTEREST',
        'SMUSE_i':'TIKTOK',
        'SMUSE_j':'BEREAL',
        'SMUSE_k':'REDDIT',
        'RACECMB':'RACE',
        'ECON1MOD':'Econ_Rating',
        'ECON1BMOD':'Econ_Outlook',  
        'RELIG':'Religion',
        'RELIMP':'Faith_Importance',
        'PRAY':'Pray_Freq'                                                                                                                    
    })

    df_combined.columns = df_combined.columns.str.title()
    return df_combined

In [25]:
df_combined = remove_and_rename_columns(df_combined)
print(df_combined.shape)
df_combined.head()

(28469, 29)

,Respid,Year,Age,Agegrp,Gender,Race,Income,Education,Region,Religion,...,Whatsapp,Linkedin,Pinterest,Tiktok,Bereal,Reddit,Econ_Rating,Econ_Outlook,Baseweight,Weight
0,1.0,2020,71.0,NaN,Female,White,"$50,000 to less than $75,000","Bachelor’s degree (for example: BA, BS)",Northeast,Agnostic,...,"No, don’t use this","No, don’t use this","No, don’t use this",NaN,NaN,NaN,Good,About the same,2.131108,0.749664
1,2.0,2020,23.0,NaN,Female,Mixed Race,"Less than $10,000",GED or alternative credential,Northeast,Nothing in particular,...,"No, don’t use this","No, don’t use this","No, don’t use this",NaN,NaN,NaN,Only fair,Worse,2.131108,3.430205
2,3.0,2020,37.0,NaN,Male,Mixed Race,"$20,000 to less than $30,000","Bachelor’s degree (for example: BA, BS)",Northeast,Protestant,...,"Yes, use this","Yes, use this","No, don’t use this",NaN,NaN,NaN,Poor,Worse,1.970167,0.881487
3,4.0,2020,70.0,NaN,Male,White,"$50,000 to less than $75,000","Master’s degree (for example: MA, MS, MEng, ME...",Northeast,Roman Catholic,...,"No, don’t use this","No, don’t use this","No, don’t use this",NaN,NaN,NaN,Only fair,Worse,1.065554,0.249154
4,5.0,2020,39.0,NaN,Male,White,"$40,000 to less than $50,000","Some college credit, but less than 1 year of c...",South,Protestant,...,"No, don’t use this","No, don’t use this","No, don’t use this",NaN,NaN,NaN,Good,Better,1.065554,0.636453

In [15]:
def replace_values(df_combined):
    # change n/a to -1 so we can convert age to float
    df_combined["Age"] = df_combined["Age"].replace({
        "n/a":"-1",
        "98+":"-1",
        "":"-1",
        'Refused':"-1"
    })

    # change column type
    df_combined["Age"] = df_combined["Age"].astype(float)

    df_combined = df_combined.replace({
        r'.*Refused.*':'Refused', 
        r'.*Something else.*':'Other',
        'Yes, use this':'Use',
        'No, don’t use this':'Don\'t Use',
        'No, don\'t use this':'Don\'t Use'
    },regex=True)

    df_combined['Gender'] = df_combined['Gender'].replace({
        "A man":"Male",
        "A woman":"Female",
        "In some other way":"Other"
    })

    df_combined["Race"] = df_combined["Race"].replace({
        r'.*Asian.*':'Asian',
        r'.*Black.*':'Black',
        r'.*other.*':'Other',
        'Mixed race':'Mixed Race'
    },regex=True)

    df_combined['Econ_Rating'] = df_combined['Econ_Rating'].replace('Only fair','Only Fair')

    df_combined["Income"] = df_combined["Income"].replace({
        r' to less than ':'-',
        r' or more':'+',
        r'Less than':'<',
        r',000':'K',
    },regex=True)

    df_combined["Education"] = df_combined["Education"].replace({
        r'.*11.*':'Some High School',
        r'.*12.*':'Some High School',
        r'.*high school.*':'High School',
        r'.*GED.*':'High School',
        r'.*college.*':'Some College',
        r'.*Associate.*':'Associate\'s Degree',
        r'.*Bachelor.*':'Bachelor\'s Degree',
        r'.*Master.*':'Master\'s Degree or Higher',
        r'.*MD.*':'Master\'s Degree or Higher',
        r'.*Doctorate.*':'Master\'s Degree or Higher',
        'Kindergarten':'N/A'
    },regex=True)

    df_combined["Religion"] = df_combined["Religion"].replace({
        r'.*Mormon.*':'Mormon',
        r'.*Orthodox.*':'Orthodox',
        r'.*Protestant.*':'Protestant'
    },regex=True)

    df_combined['Marital'] = df_combined['Marital'].replace({
        "Separated":"Divorced",
        "Never been married":"Never married",
    })
    return df_combined

In [26]:
df_combined = replace_values(df_combined)
print(df_combined.shape)
df_combined.head()

(28469, 29)

,Respid,Year,Age,Agegrp,Gender,Race,Income,Education,Region,Religion,...,Whatsapp,Linkedin,Pinterest,Tiktok,Bereal,Reddit,Econ_Rating,Econ_Outlook,Baseweight,Weight
0,1.0,2020,71.0,NaN,Female,White,$50K-$75K,Bachelor's Degree,Northeast,Agnostic,...,Don't Use,Don't Use,Don't Use,NaN,NaN,NaN,Good,About the same,2.131108,0.749664
1,2.0,2020,23.0,NaN,Female,Mixed Race,< $10K,High School,Northeast,Nothing in particular,...,Don't Use,Don't Use,Don't Use,NaN,NaN,NaN,Only Fair,Worse,2.131108,3.430205
2,3.0,2020,37.0,NaN,Male,Mixed Race,$20K-$30K,Bachelor's Degree,Northeast,Protestant,...,Use,Use,Don't Use,NaN,NaN,NaN,Poor,Worse,1.970167,0.881487
3,4.0,2020,70.0,NaN,Male,White,$50K-$75K,Master's Degree or Higher,Northeast,Roman Catholic,...,Don't Use,Don't Use,Don't Use,NaN,NaN,NaN,Only Fair,Worse,1.065554,0.249154
4,5.0,2020,39.0,NaN,Male,White,$40K-$50K,Some College,South,Protestant,...,Don't Use,Don't Use,Don't Use,NaN,NaN,NaN,Good,Better,1.065554,0.636453

In [17]:
def create_calculated_columns(df_combined):
    # conditions for each group
    conditions = [
        df_combined['Income'].isin(['$10K-$20K','$20K-$30K','$30K-$40K','< $10K','< $30K']),
        df_combined['Income'].isin(['$40K-$50K','$50K-$60K','$60K-$70K','$50K-$70K']),
        df_combined['Income'].isin(['$70K-$100K','$70K-$80K','$70K-$90K','$75K-$100K','$80K-$90K','$90K-$100K']),
        df_combined['Income'].isin(['$100K+','$100K-$125K','$100K-$150K','$125K-$150K','$150K+']),
        df_combined['Income'] == 'Refused'
    ]
    # corresponding groups for each condition
    group = ['< $40K','$40-70K','$70-100K','$100K+','Refused']

    # insert new column after INCOME
    df_combined.insert(
        df_combined.columns.get_loc('Income') + 1, # position we want to insert at
        'Income_Cat', # name of new column
        np.select(conditions, group, default='Refused') # set value according to conditions 
    )

    conditions = [
        (df_combined['Agegrp'] == '18-24') | ((18 <= df_combined['Age']) & (df_combined['Age'] <= 24)),
        (df_combined['Agegrp'].isin(['25-29','30-34','35-39'])) | ((25 <= df_combined['Age']) & (df_combined['Age'] <= 39)),
        (df_combined['Agegrp'].isin(['40-44','45-49','50-54','55-59'])) | ((40 <= df_combined['Age']) & (df_combined['Age'] <= 59)),
        (df_combined['Agegrp'].isin(['60-64','65-69','70-74','75-79'])) | ((60 <= df_combined['Age']) & (df_combined['Age'] <= 79)),
        (df_combined['Agegrp'] == '80+')| (80 <= df_combined['Age']),
        (df_combined['Agegrp'] == 'Refused') | (df_combined['Age'] == -1)
    ]
    group = ['18-24','25-39','40-59','60-79','80+','Refused']

    df_combined.insert(
        df_combined.columns.get_loc('Agegrp') + 1, # position we want to insert at
        'Age_Cat', # name of new column
        np.select(conditions, group, default='Refused') # set value according to conditions 
    )

    conditions = [
        (df_combined['Econ_Rating'].isin(['Good','Excellent'])),
        (df_combined['Econ_Rating'].isin(['Poor','Only Fair']))
    ]
    sentiment = ['Positive', 'Negative']

    # create a new column that labels each rating as negative or positive
    df_combined.insert(
        df_combined.columns.get_loc('Econ_Rating') + 1, # position we want to insert at
        'Econ_Rating_Cat', # name of new column
        np.select(conditions, sentiment, default='Refused') # set value according to conditions 
    )

    conditions = [
        (df_combined['Econ_Outlook'].isin(['About the same','Better'])),
        (df_combined['Econ_Outlook'] == 'Worse')
    ]
    sentiment = ['Positive', 'Negative']

    # create a new column that labels each rating as negative or positive
    df_combined.insert(
        df_combined.columns.get_loc('Econ_Outlook') + 1, # position we want to insert at
        'Econ_Outlook_Cat', # name of new column
        np.select(conditions, sentiment, default='Refused') # set value according to conditions 
    )

    conditions = [
        ((df_combined['Econ_Outlook'] == 'Better') | ((df_combined['Econ_Outlook'] == 'About the same') & (df_combined['Econ_Rating_Cat'] == 'Positive'))),
        ((df_combined['Econ_Outlook'] == 'Worse') | ((df_combined['Econ_Outlook'] == 'About the same') & (df_combined['Econ_Rating_Cat'] == 'Negative')))
    ]
    sentiment = ['Positive', 'Negative']

    # create a new column that labels each rating as negative or positive
    df_combined.insert(
        df_combined.columns.get_loc('Econ_Outlook_Cat') + 1, # position we want to insert at
        'Econ_Rating_Outlook', # name of new column
        np.select(conditions, sentiment, default='Refused') # set value according to conditions 
    )
    return df_combined

In [27]:
df_combined = create_calculated_columns(df_combined)
print(df_combined.shape)
df_combined.head()

(28469, 34)

,Respid,Year,Age,Agegrp,Age_Cat,Gender,Race,Income,Income_Cat,Education,...,Tiktok,Bereal,Reddit,Econ_Rating,Econ_Rating_Cat,Econ_Outlook,Econ_Outlook_Cat,Econ_Rating_Outlook,Baseweight,Weight
0,1.0,2020,71.0,NaN,60-79,Female,White,$50K-$75K,Refused,Bachelor's Degree,...,NaN,NaN,NaN,Good,Positive,About the same,Positive,Positive,2.131108,0.749664
1,2.0,2020,23.0,NaN,18-24,Female,Mixed Race,< $10K,< $40K,High School,...,NaN,NaN,NaN,Only Fair,Negative,Worse,Negative,Negative,2.131108,3.430205
2,3.0,2020,37.0,NaN,25-39,Male,Mixed Race,$20K-$30K,< $40K,Bachelor's Degree,...,NaN,NaN,NaN,Poor,Negative,Worse,Negative,Negative,1.970167,0.881487
3,4.0,2020,70.0,NaN,60-79,Male,White,$50K-$75K,Refused,Master's Degree or Higher,...,NaN,NaN,NaN,Only Fair,Negative,Worse,Negative,Negative,1.065554,0.249154
4,5.0,2020,39.0,NaN,25-39,Male,White,$40K-$50K,$40-70K,Some College,...,NaN,NaN,NaN,Good,Positive,Better,Positive,Positive,1.065554,0.636453

In [28]:
utils.write_to_file(df_combined, 'Datasets/combined_dataset.csv')

# Exploratory Data Analysis